Lecturer page..........
cs-dept-ibbul/vlab pull request #57
Opened 2021-03-12 13:41 UTC by balqees0325

Lecturer page, Admin and Students guide pages added to the docs

2021-03-14 19:38 UTC, Auwalms approved these changes
LGTM

2021-03-15 06:45 UTC, abdullahikawu requested changes
Are you able to add a screenshot to the PR, it makes it easier for review and to see how this renders.

2021-03-15 06:47 UTC, balqees0325 commented
alright sir, i forgot you did mention the last time too . pardon me


On Mon, Mar 15, 2021 at 7:45 AM Abdullahi Abubakar Kawu <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Are you able to add a screenshot to the PR, it makes it easier for review
> and to see how this renders.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cs-dept-ibbul/vlab/pull/57#pullrequestreview-611865483>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AP5QEVAMV7GHMJJG75YT6JTTDWUJNANCNFSM4ZCJ5CYA>
> .
>

2021-03-16 14:18 UTC, abdullahikawu approved these changes

2021-03-16 14:19 UTC, merged