feat: instructor view student, admin manage faculty
cs-dept-ibbul/vlab pull request #83
Opened 2021-04-04 16:25 UTC by saidabdul80

2021-04-05 17:55 UTC, Auwalms reviewed
Nice job, please remove the .gitignore and update the type @saidabdul80

2021-04-05 17:55 UTC, Auwalms commented on .gitignore
> +.gitignore
Please do not ignore .gitignore. it will mean all the folders that shouldn't get to the version control gets send there @saidabdul80

2021-04-05 17:55 UTC, Auwalms commented on resources/js/components/faculty.vue
> +					      cancelButtonText:'Cancle',
Typography here. Cancel not cancle 😜😜😜😜 @saidabdul80

2021-04-05 18:19 UTC, abdullahikawu requested changes
Review the comments from @Auwalms

2021-04-07 09:43 UTC, Auwalms approved these changes
Good to Go.

2021-04-07 17:08 UTC, abdullahikawu approved these changes

2021-04-07 17:36 UTC, merged