Courses
cs-dept-ibbul/vlab pull request #95
Opened 2021-04-07 22:06 UTC by bynalab

2021-04-08 05:06 UTC, Auwalms requested changes
Confirm the changes requested.

2021-04-08 05:06 UTC, Auwalms commented on app/Http/Controllers/Api/CourseController.php
> +            return response()->json(['error' => 'No course with this id'], 200);
@bynalab don't you think using error code 404 here will be ideal since the resource is actually not found or does not exist?

2021-04-08 05:06 UTC, Auwalms commented on app/Http/Controllers/Api/CourseController.php
> +            if(empty($request->get('school_id')) && empty($request->get('faculty_id')) && empty($request->get('title')) && empty($request->get('code'))){
Since you want to validate if all of them are not empty, don't you think using || will be more appropriate than &&? @bynalab

2021-04-08 05:06 UTC, Auwalms commented on app/Http/Controllers/Api/CourseController.php
> +            return response()->json(['error' => 'No course with this id'], 200);
Don't you think 404 is ideal here? @bynalab. So we can reserve 200 for only success requests.

2021-04-08 05:06 UTC, Auwalms commented on app/Http/Controllers/Api/FacultyController.php
> +            return response()->json(['error' => 'No faculty with this id'], 200);
200 or 404 @bynalab ???

2021-04-08 05:06 UTC, Auwalms commented on app/Http/Controllers/Api/FacultyController.php
> +            if(empty($facultyName) && empty($facultyCode) && empty($schoolID)){
|| or &&? Which way @bynalab

2021-04-08 05:06 UTC, Auwalms commented on app/Http/Controllers/Api/FacultyController.php
> +            return response()->json(['error' => 'No faculty with this id'], 200);
Check status code @bynalab

2021-04-08 05:07 UTC, Auwalms commented
@bynalab please also resolve merge conflict.

2021-04-08 05:23 UTC, bynalab commented on app/Http/Controllers/Api/CourseController.php
> +            if(empty($request->get('school_id')) && empty($request->get('faculty_id')) && empty($request->get('title')) && empty($request->get('code'))){
I'm validating if all of them are empty, I don't want to border the db if all are empty. I think && is the right way.

2021-04-08 05:24 UTC, bynalab commented on app/Http/Controllers/Api/CourseController.php
> +            return response()->json(['error' => 'No course with this id'], 200);
I agree, copy and paste is the root of all evil. I'll rectify.

2021-04-08 06:00 UTC, saidabdul80 reviewed
Waiting for response

2021-04-08 06:00 UTC, saidabdul80 commented on app/Http/Controllers/Api/CourseController.php
> +            $request->get('school_id') != null ? $course->school_id = $request->get('school_id') : null;
Please get school_id from the database and if it's does not exist let return a system configuration error: school has not been created. Or you can fetch it and keep it somewhere maybe in session when the user logged in, so u can retrieve it any time there's need

2021-04-08 06:00 UTC, saidabdul80 commented on app/Http/Controllers/Api/FacultyController.php
> +        $schoolID = $request->get('school_id');
same here as above comment

2021-04-08 06:00 UTC, saidabdul80 commented on app/Http/Controllers/Api/CourseController.php
> +            $request->get('school_id') != null ? $course->school_id = $request->get('school_id') : null;
Let get school I'd from the db or use any best method to do that but note that it's not coming from a request. maybe save in session or somewhere else for future use when the user logged in

2021-04-08 06:00 UTC, saidabdul80 commented on app/Http/Controllers/Api/FacultyController.php
> +        $schoolID = $request->get('school_id');
Same here

2021-04-08 07:20 UTC, Auwalms requested changes
Please check updated comments.

2021-04-08 07:20 UTC, Auwalms commented on app/Http/Controllers/Api/CourseController.php
> +            return response()->json(['error' => 'No course with this id'], 200);
You still missed this @bynalab

2021-04-08 07:20 UTC, Auwalms commented on app/Http/Controllers/Api/CourseController.php
> +                return response()->json(['success' => true], 401);
Success should be in the 2XX code, basically 200 in this case not 401 or even 201. @bynalab

2021-04-08 07:20 UTC, Auwalms commented on app/Http/Controllers/Api/CourseController.php
> +        return response()->json(['success' => false], 200);
Why success and false with a 200 even? Care to explain? @bynalab

2021-04-08 07:20 UTC, Auwalms commented on app/Http/Controllers/Api/FacultyController.php
> +            return response()->json(['error' => 'No faculty with this id'], 200);
This should be 404 @bynalab

2021-04-08 07:20 UTC, Auwalms commented on app/Http/Controllers/Api/FacultyController.php
> +            return response()->json(['error' => 'No faculty with this id'], 400);
404 sir @bynalab

2021-04-08 07:22 UTC, bynalab commented on app/Http/Controllers/Api/CourseController.php
> +            return response()->json(['error' => 'No course with this id'], 200);
Nah... That's why I used "fixing" as commit. My laptop is off and I have to push so I can continue from somewhere else.

2021-04-08 07:24 UTC, Auwalms commented on app/Http/Controllers/Api/CourseController.php
> +            return response()->json(['error' => 'No course with this id'], 200);
Oh okay. Also please pull the current repo into your project and resolve the merge conflict when you are done.

2021-04-09 10:01 UTC, abdullahikawu requested changes
please effect changes requested by @Auwalms

2021-04-09 16:36 UTC, Auwalms approved these changes
GTG

2021-04-09 16:42 UTC, merged